"""add exercises and training plans

Revision ID: 3d0d083d605c
Revises: 5727ef39316f
Create Date: 2026-04-26 14:13:01.179943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d0d083d605c'
down_revision: Union[str, Sequence[str], None] = '5727ef39316f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('grupo_muscular', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercicios_grupo_muscular'), 'exercicios', ['grupo_muscular'], unique=False)
    op.create_index(op.f('ix_exercicios_nome'), 'exercicios', ['nome'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('prescricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treino_id', sa.Integer(), nullable=True),
    sa.Column('exercicio_id', sa.Integer(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticoes', sa.String(), nullable=True),
    sa.Column('descanso', sa.Integer(), nullable=True),
    sa.Column('carga', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercicio_id'], ['exercicios.id'], ),
    sa.ForeignKeyConstraint(['treino_id'], ['treinos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_prescricoes_exercicio_nome_exercicio'), table_name='prescricoes_exercicio')
    op.drop_table('prescricoes_exercicio')
    op.drop_column('planos_treino', 'data_fim')
    op.drop_column('planos_treino', 'data_criacao')
    op.drop_column('sessoes_treino', 'reposicao_agendada')
    op.add_column('treinos', sa.Column('plano_id', sa.Integer(), nullable=True))
    op.add_column('treinos', sa.Column('ordem', sa.Integer(), nullable=True))
    op.alter_column('treinos', 'nome',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('fk_plano'), 'treinos', type_='foreignkey')
    op.create_foreign_key(None, 'treinos', 'planos_treino', ['plano_id'], ['id'], ondelete='CASCADE')
    op.drop_column('treinos', 'plano_treino_id')
    op.drop_column('treinos', 'descricao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treinos', sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('treinos', sa.Column('plano_treino_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'treinos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_plano'), 'treinos', 'planos_treino', ['plano_treino_id'], ['id'], ondelete='CASCADE')
    op.alter_column('treinos', 'nome',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('treinos', 'ordem')
    op.drop_column('treinos', 'plano_id')
    op.add_column('sessoes_treino', sa.Column('reposicao_agendada', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('planos_treino', sa.Column('data_criacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('planos_treino', sa.Column('data_fim', sa.DATE(), autoincrement=False, nullable=True))
    op.create_table('prescricoes_exercicio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_exercicio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('series', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('repeticoes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('carga_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tempo_descanso_segundos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notas_tecnicas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('treino_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('prescricoes_exercicio_pkey'))
    )
    op.create_index(op.f('ix_prescricoes_exercicio_nome_exercicio'), 'prescricoes_exercicio', ['nome_exercicio'], unique=False)
    op.drop_table('prescricoes')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_exercicios_nome'), table_name='exercicios')
    op.drop_index(op.f('ix_exercicios_grupo_muscular'), table_name='exercicios')
    op.drop_table('exercicios')
    # ### end Alembic commands ###
