"""add student status

Revision ID: 9d90b56e2675
Revises: e85ce345def4
Create Date: 2026-05-03 15:50:30.055847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d90b56e2675'
down_revision: Union[str, Sequence[str], None] = 'e85ce345def4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alunos', 'status')
    # ### end Alembic commands ###
