"""make aluno_id optional and add duracao_semanas to planos_treino

Revision ID: dbaa45ac26b4
Revises: 9d90b56e2675
Create Date: 2026-05-03 16:39:08.562807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbaa45ac26b4'
down_revision: Union[str, Sequence[str], None] = '9d90b56e2675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planos_treino', sa.Column('duracao_semanas', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planos_treino', 'duracao_semanas')
    # ### end Alembic commands ###
