"""add_tipo_pagamento_e_saldo_aulas

Revision ID: e85ce345def4
Revises: 3d0d083d605c
Create Date: 2026-05-03 13:58:26.426668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85ce345def4'
down_revision: Union[str, Sequence[str], None] = '3d0d083d605c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Adiciona as colunas permitindo nulo inicialmente
    op.add_column('alunos', sa.Column('tipo_pagamento', sa.String(), nullable=True, server_default='mensal'))
    op.add_column('alunos', sa.Column('saldo_aulas', sa.Integer(), nullable=True, server_default='0'))
    
    # 2. Popula dados legados (caso existam)
    op.execute("UPDATE alunos SET tipo_pagamento = 'mensal' WHERE tipo_pagamento IS NULL")
    op.execute("UPDATE alunos SET saldo_aulas = 0 WHERE saldo_aulas IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alunos', 'saldo_aulas')
    op.drop_column('alunos', 'tipo_pagamento')
    # ### end Alembic commands ###
